config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  get 'contact' => 'pages#contact', as: 'contact'
  get 'our-story' => 'pages#story', as: 'story'
  get 'donate' => 'pages#donate', as: 'donate'
  get 'email-updates' => 'pages#updates', as: 'updates'
  get 'sponsorships' => 'pages#sponsorships', as: 'sponsorships'
  get 'projects' => 'pages#projects', as: 'projects'
  get 'email-updates' => 'pages#email_updates', as: 'email_updates'
  get 'frequently-asked-questions' => 'pages#faq', as: 'faq'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def home_alt
  end

  def contact
  end

  def story
  end

  def donate
  end

  def updates
  end

  def sponsorships
  end

  def projects
  end

  def email_updates
  end

  def faq
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matumaini's Mission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice.present? || alert.present? %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/_footer.html.erb
<div class="bottomNav">
			<nav class="navbar-sec navbar-secondary" role="navigation">
			  <div class="container">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example			-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a href="/" class="navbar-brand-secondary">BE A CONDUIT FOR HOPE</a>
			    </div>
			
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <!--<ul class="nav navbar-nav">
			        <li class="active"><a href="#">Link</a></li>
			        <li><a href="#">Link</a></li>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			            <li class="divider"></li>
			            <li><a href="#">One more separated link</a></li>
			          </ul>
			        </li>
			      </ul>-->
			      
			      <ul class="nav navbar-nav navbar-right">
			        <li><%= link_to "DONATE", donate_path %></li>
			        <li><%= link_to "SPONSOR A CHILD", sponsorships_path %></li>
			        <!--<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			          </ul>
			        </li>-->
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		</div>


		<!-- FOOTER -->
<section class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<h3 class="partner">Partner with us in bringing hope</h3>
				<%= link_to "Get Email Updates", email_updates_path, class: "btn btn-home" %>
			</div>
			<div class="col-md-5">
				<p class="contactHeader">Contact Us</p>
				<p class="contactText">Main: 615-512-7579</p>
				<p class="contactText">harmony@matumainismission.com</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<p class="ftrCopy">&copy; 2014 Matumaini's Mission | 501(c)3</p>
				<p class="ftrText">Site by <%= link_to "Big Moon Creative", "http://bigmooncreative.com", class: "bmc-blue" %></p>
			</div>
		</div>
	</div>

</section>

app/views/pages/_topnav.html.erb
<!-- NAV -->
		<div class="topNav">
			<nav class="navbar navbar-op" role="navigation">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example			-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a href="/" class="navbar-brand"><img src="assets/logoNav.png" /></a>
			    </div>
			
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <!--<ul class="nav navbar-nav">
			        <li class="active"><a href="#">Link</a></li>
			        <li><a href="#">Link</a></li>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			            <li class="divider"></li>
			            <li><a href="#">One more separated link</a></li>
			          </ul>
			        </li>
			      </ul>-->
			      
			      <ul class="nav navbar-nav navbar-right">
			        <!--<li>
			        	<%= link_to_unless_current "OUR STORY", story_path do 
			        		link_to "OUR STORY", story_path, class: "active-nav"
			        	end %>
			        </li>-->
			        <li>
			        	<%= link_to_unless_current "OUR STORY", story_path do
			        		link_to "OUR STORY", story_path, class: "active-nav"
			        	end %>
			        </li>
			        <li>
			        	<%= link_to_unless_current "DONATE", donate_path do
			        		link_to "DONATE", donate_path, class: "active-nav"
			        	end %>
			        </li>
			        <li>
			        	<%= link_to_unless_current "SPONSORSHIPS", sponsorships_path do
			        		link_to "SPONSORSHIPS", sponsorships_path, class: "active-nav"
			        	end %>
			        </li>
			        <li>
			        	<%= link_to_unless_current "HOW CAN I HELP?", projects_path do
			        		link_to "HOW CAN I HELP?", projects_path, class: "active-nav"
			        	end %>
			        </li>
			        <li>
			        	<%= link_to_unless_current "EMAIL UPDATES", updates_path do
			        		link_to "EMAIL UPDATES", updates_path, class: "active-nav"
			        	end %>
			        </li>
			        <li>
			        	<%= link_to_unless_current "FAQ", faq_path do
			        		link_to "FAQ", faq_path, class: "active-nav"
			        	end %>
			        </li>

			        <!--<li>
			        	<%= link_to_unless_current "PROJECTS", projects_path do
			        		link_to "PROJECTS", projects_path, class: "active-nav"
			        	end %>
			        </li>-->
			        <!--<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			          </ul>
			        </li>-->
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		</div>
		<!-- END TOPNAV -->

app/views/pages/contact.html.erb
<div class="secondary-top"></div>
<%= render 'topnav' %>


<!-- SIGN UP FORM -->
<section class="contact-form">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="contact-hdr">Partner with us in bringing hope</h2>
				<p class="contact-text">Provide the information below to receive updates on how your prayers and donations are impacting children in Rwanda and the DNC Africa.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div id="mc_embed_signup">
					<form action="//matumainismission.us8.list-manage.com/subscribe/post?u=b0562c03cbb8c5681b8fec762&amp;	id=f7033b6ad9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="	validate" target="_blank" novalidate>
						<div class="form-group">
							<label for="mce-Email">Email</label>
							<input type="email" value="" name="EMAIL" id="mce-Email" class="form-control" />
						</div>
						<div class="form-group">
							<label for="mce-FNAME">First Name</label>
							<input type="text" name="FNAME" value="" id="mce-FNAME" class="form-control" />
						</div>
						<div class="form-group">
							<label for="mce-LNAME">Last Name</label>
							<input type="text" name="LNAME" value="" id="mce-LNAME" class="form-control" />
						</div>
						
							<!-- real people should not fill this in and expect good things - do not remove this or risk form 	bot signups-->
							<div style="position: absolute; left: -5000px;"><input type="text" name="	b_b0562c03cbb8c5681b8fec762_f7033b6ad9" tabindex="-1" value=""></div>
							<button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-home">Subscribe</button>
					</form>
				</div>
				<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

				<p class="contact-text-btm">After submitting your information check for a confirmation email.</p>
			</div>
			
		</div>
	</div>
	
</section>

<div class="bottomNav">
			<nav class="navbar-sec navbar-secondary" role="navigation">
			  <div class="container">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example			-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a href="/" class="navbar-brand-secondary">BE A CONDUIT FOR HOPE</a>
			    </div>
			
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <!--<ul class="nav navbar-nav">
			        <li class="active"><a href="#">Link</a></li>
			        <li><a href="#">Link</a></li>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			            <li class="divider"></li>
			            <li><a href="#">One more separated link</a></li>
			          </ul>
			        </li>
			      </ul>-->
			      
			      <ul class="nav navbar-nav navbar-right cl-effect-4-1">
			        <li><a href="#">DONATE</a></li>
			        <li><a href="#">SPONSOR A CHILD</a></li>
			        <!--<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"			></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			          </ul>
			        </li>-->
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		</div>


		<!-- FOOTER -->
<section class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<h3 class="partner">Partner with us in bringing hope</h3>
				<%= link_to "Get Email Updates", contact_path, class: "btn btn-home" %>
			</div>
			<div class="col-md-5">
				<p class="contactHeader">Contact Us</p>
				<p class="contactText">Main: 123-456-7890</p>
				<p class="contactText">harmony@matumainismission.com</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<p class="ftrCopy">&copy; 2014 Matumaini's Mission | Privacy Policy</p>
				<p class="ftrText">Site by <%= link_to "Big Moon Creative", "http://bigmooncreative.com", class: "bmc-blue" %></p>
			</div>
		</div>
	</div>

</section>

app/views/pages/donate.html.erb
<div class="donate-top"></div>
<%= render 'topnav' %>




<section class="donate-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="contact-hdr">How can you help?</h2>
			</div>
		</div>	
	</div>


	<div class="container">
		<div class="row">
			<div class="col-md-4 nopadding">
				<div class="donate-box">
					<h3>Donate</h3>
					<p>Every dollar given goes towards fulfilling the sponsorship needs for a child in need. Once those funds have been raised we apply gifts to the next child on the list. Everything that you give goes towards meeting those needs.</p>
					<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
					<input type="hidden" name="cmd" value="_s-xclick">
					<input type="hidden" name="hosted_button_id" value="PGN2JEC8SA76Y">

					<p class="text-center"><button name="submit" class="btn btn-home">Donate Now</button></p>
					<!--<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
					<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">-->
					</form>
				</div>
			</div>
			<div class="col-md-4 nopadding edges">
				<div class="donate-box">
					<h3 class="help-hdr">Sponsor a child</h3>
					<p>We believe a sponsorship is more than just food or just schooling. That's why we have combined the sponsorship and made it possible to give these children both. We have taken the total cost of one years food,school fees, school supplies, uniform, and shoes. We have broken down the cost over the course of 12 months making it affordable for you and realistic. Once you've chosen to sponsor a child, you will receive the child's photo and information in the mail. Then look for monthly updates through email, as we visit the children and drop off their food.</p>
					<p class="text-center"><%= link_to "SPONSOR a CHild", sponsorships_path, class: "btn btn-home" %></p>
				</div>
			</div>
			<div class="col-md-4 nopadding">
				<div class="donate-box">
					<h3>Pray</h3>
					<p> We know when God is on our side anything is possible. Your prayers for these children and this mission are important and are felt. If you would like be updated on upcoming projects and other updates, please join our email list for periodic emails.</p>
					<p class="text-center"><%= link_to "GET UPDATES", updates_path, class: "btn btn-home" %></p>
				</div>
			</div>
		</div>
	</div>
	
</section>








<%= render 'footer' %>

app/views/pages/email_updates.html.erb
<div class="secondary-top"></div>
<%= render 'topnav' %>


<!-- SIGN UP FORM -->
<section class="contact-form">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="contact-hdr">Partner with us in bringing hope</h2>
				<p class="contact-text">Provide the information below to receive updates on how your prayers and donations are impacting children in Rwanda and the DRC Africa.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div id="mc_embed_signup">
					<form action="//matumainismission.us8.list-manage.com/subscribe/post?u=b0562c03cbb8c5681b8fec762&amp;	id=f7033b6ad9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="	validate" target="_blank" novalidate>
						<div class="form-group">
							<label for="mce-Email">Email</label>
							<input type="email" value="" name="EMAIL" id="mce-Email" class="form-control" />
						</div>
						<div class="form-group">
							<label for="mce-FNAME">First Name</label>
							<input type="text" name="FNAME" value="" id="mce-FNAME" class="form-control" />
						</div>
						<div class="form-group">
							<label for="mce-LNAME">Last Name</label>
							<input type="text" name="LNAME" value="" id="mce-LNAME" class="form-control" />
						</div>
						
							<!-- real people should not fill this in and expect good things - do not remove this or risk form 	bot signups-->
							<div style="position: absolute; left: -5000px;"><input type="text" name="	b_b0562c03cbb8c5681b8fec762_f7033b6ad9" tabindex="-1" value=""></div>
							<button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-home">Subscribe</button>
					</form>
				</div>
				<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

				<p class="contact-text-btm">After submitting your information check for a confirmation email.</p>

				<!--
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
					<input type="hidden" name="cmd" value="_s-xclick">
					<input type="hidden" name="hosted_button_id" value="PGN2JEC8SA76Y">
					<button name="submit" class="btn btn-home">Donate</button>
					<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
				</form>
				-->



			</div>
			
		</div>
	</div>
	
</section>

<%= render 'footer' %>

app/views/pages/faq.html.erb
<div class="faq-top"></div>
<%= render 'topnav' %>

<section class="faq-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="contact-hdr">Frequently Asked Questions</h2>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h3 class="faq-question">How much of my donation goes to administrative costs?</h3>
				<p class="faq-answer">None!! We raise funds in other ways to pay for website costs, etc.</p>
				<h3 class="faq-question">What does the sponsorship money buy?</h3>
				<p class="faq-answer">The sponsorship gives the child all the school supplies (paper, pencils, 	backpack etc), School fees, food, 2 uniforms a year, and 2 pairs of shoes per 	year</p>
				<h3 class="faq-question">How can only $34 a month pay for all of that?</h3>
				<p class="faq-answer"> The program is broken down over 12 months, the total yearly cost is $408. 	Some months are more expensive than others but at the end of the 12 months it 	all averages out so we are able to give the child what they need each month 	without asking for more money from the sponsor. </p>
				<h3 class="faq-question">Will I get updates?</h3>
				<p class="faq-answer">Yes, monthly updates and photos are given.</p>
				<h3 class="faq-question">Can I send my child more?</h3>
				<p class="faq-answer">Yes, if you would like to mail your child a photo of your family let us know 	we can give you an address. It is expensive to send a package but you are 	welcome to do that as well. If you want to give you child something extra maybe 	during the holidays, you can specify what you want purchased and we can buy it 	in country.</p>
				<h3 class="faq-question">Can I pick the child I sponsor?</h3>
				<p class="faq-answer">If that is something that is important to you then we can make that happen, 	but we know which children are in desperate need, so the child you receive 	needs you. Each child is special to Matumaini's Mission and which ever way you 	decide you will still be making a difference in a child's life which is the 	most important thing.</p>
				<h3 class="faq-question">Can I share my sponsored child on social media?</h3>
				<p class="faq-answer">Yes, we love you to share your child with others and show the good work you 	are doing. We do ask that you put our website link in the caption of the picture	.</p>
				<h3 class="faq-question">What happens when I pay the sponsorship fee?</h3>
				<p class="faq-answer">The first photo and profile letter will come in the mail shortly after. You 	will receive a photo and profile of the child you will be sponsoring. The rest 	of the updates come by email unless otherwise specified.</p>
				<h3 class="faq-question"> Can the sponsorship or donation be a tax write off?</h3>
				<p class="faq-answer">Yes, Matumaini's Mission is registered with the IRS as a 501c3 non-profit. 	If you need extra receipts other than your paypal payment receipt for tax 	purposes just email us, we will gladly give you a yearly breakdown. </p>
				<h3 class="faq-question">How does the money reach the child?</h3>
				<p class="faq-answer">We do not hand cash to any child. We have in country staff that purchase the 	items then gives them to the child, as well as goes directly to the school and 	pays the fees. Matumaini's Mission in the states then receives all receipts and 	photos to keep on file.</p>
			</div>
			<div class="col-md-4">
	
			</div>
		</div>
	</div>
</section>

<%= render 'footer' %>

app/views/pages/home.html.erb
<section>
	<div class="topHome">

		<%= render 'topnav' %>
	
		<div class="container-fluid">
			
			<div class="row">
				<div class="col-md-3 col-md-offset-9">
					<div class="btn-box">
						<p class="text-center"><%= link_to "Donate Now", donate_path, class: "btn btn-home btn-block" %></p>
						<p class="text-center"><%= link_to "Sponsor a Child", sponsorships_path, class: "btn btn-home btn-block" %></p>
						<!--<p class="btn-text">Spondor a child for as little as $34 a month. Find out how.</p>-->
					</div>
				</div>
			</div>
			
		</div>


	</div>
</section>

<section class="callToAction">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-1 col-md-10">
				<p class="missionStatement text-center">Matumaini means "Hope" in Swahili. Our mission is to bring just that to under privileged widows and orphans in Rwanda and DRC Africa.</p>
			
				<!--<p class="text-center"><%= link_to "Learn more about Matumaini's Mission", story_path, class: "missionSL" %></p>-->
			</div>
		</div>
	</div>
</section>


<!-- BOXES SECTION -->
<section class="boxes">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				
				<div class="view view-first">
					<%= image_tag "donate.jpg", class: "img-rouded img-responsive", alt: "img" %>
					<div class="mask">
						<h2>Donate</h2>
						<!--<p>This is text that will appear in the box when I hover over it.</p>-->
						<%= link_to "Read More", donate_path, class:"btn btn-home btn-sm" %>
					</div>
				</div>
				<p class="text-center box-text">Learn how you can bring hope to a child in need</p> 
			</div>
			<div class="col-md-3">
				<div class="view view-first">
					<%= image_tag "sponsorship.jpg", class: "img-rouded img-responsive", alt: "img" %>
					<div class="mask">
						<h2>Sponsorships</h2>
						<!--<p>This is text that will appear in the box when I hover over it.</p>-->
						<%= link_to "Read More", sponsorships_path, class:"btn btn-home btn-sm" %>
					</div>
				</div>
				<p class="text-center box-text">Learn about how you can sponsor a child in need</p>  
			</div>
			<div class="col-md-3">
				<div class="view view-first">
					<%= image_tag "kids.jpg", class: "img-rouded img-responsive", alt: "img" %>
					<div class="mask">
						<h2>Our Story</h2>
						<!--<p>This is text that will appear in the box when I hover over it.</p>-->
						<%= link_to "Read More", story_path, class:"btn btn-home btn-sm" %>
					</div>
				</div>
				<p class="text-center box-text">Learn more about Matumaini's Mission</p> 
			</div>
			<div class="col-md-3">
				<div class="view view-first">
					<%= image_tag "spotlight.jpg", class: "img-rouded img-responsive", alt: "img" %>
					<div class="mask">
						<h2>Projects</h2>
						<!--<p>This is text that will appear in the box when I hover over it.</p>-->
						<%= link_to "Read More", projects_path, class:"btn btn-home btn-sm" %>
					</div>
				</div>
				<p class="text-center box-text">Learn more about our current projects</p> 
			</div>
			
		</div>
	</div>
</section>


<%= render 'footer' %>